engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true

ratings:
  paths:
  - "src/*.js"
  - "src/*.coffee"

exclude_paths: []
